name: NvrEndingTxt
options:
  bundleIdPrefix: com.nvr
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.0.0"

settings:
  base:
    MARKETING_VERSION: "1.1.9"
    CURRENT_PROJECT_VERSION: "11"
    DEVELOPMENT_TEAM: "454K5WYH9Y"

targets:
  NvrEndingTxt:
    type: application
    platform: macOS
    sources:
      - NvrEndingTxt
    dependencies:
      - package: KeyboardShortcuts
      - package: Sparkle
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nvr.NvrEndingTxt
        INFOPLIST_FILE: NvrEndingTxt/Info.plist
        CODE_SIGN_ENTITLEMENTS: NvrEndingTxt/NvrEndingTxt.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configurations:
        Release:
          CODE_SIGN_IDENTITY: "-"
    info:
      path: NvrEndingTxt/Info.plist
      properties:
        LSUIElement: true
        CFBundleDisplayName: endless.txt
        NSHumanReadableCopyright: ""
        SUFeedURL: https://raw.githubusercontent.com/starigade/endless.txt/main/appcast.xml
        SUPublicEDKey: 2a/2nd2lvGvv5z7jG/i+LystWjXckMSp1aY+axB8L0g=
    scheme:
      gatherCoverageData: false
